projects:
  feetyour:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: kussfjitbbdyje6zwzesg7fhre
      endpoints:
        prod: >-
          https://ezz43apcbbdifgb4dhrxyb4x3y.appsync-api.ap-southeast-2.amazonaws.com/graphql
